<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Save</name>
   <tag></tag>
   <elementGuidId>c76d62d6-dbb7-4789-9075-e11fd08352d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-root']/div/div[2]/div/div/div/div/form/div[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>26f7b44b-c686-4486-8f3b-41ebdc467aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormControl-root MuiFormControl-marginNormal MuiFormControl-fullWidth</value>
      <webElementGuid>b83479b2-8b5a-446e-82ba-e49e1cd9686a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>8a30edc3-4a5d-497e-986a-40c37dacdbfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/div[@class=&quot;makeStyles-root-3419&quot;]/div[@class=&quot;makeStyles-main-3417&quot;]/div[@class=&quot;makeStyles-content-3416&quot;]/div[@class=&quot;makeStyles-container-3448&quot;]/div[@class=&quot;MuiGrid-root makeStyles-fullHeight-3477 MuiGrid-container&quot;]/div[@class=&quot;MuiGrid-root makeStyles-content-3476 MuiGrid-item MuiGrid-grid-xs-4&quot;]/form[1]/div[@class=&quot;MuiFormControl-root MuiFormControl-marginNormal MuiFormControl-fullWidth&quot;]</value>
      <webElementGuid>5a433c4a-6306-4477-abb3-47995eb409f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div/div[2]/div/div/div/div/form/div[6]</value>
      <webElementGuid>af082171-5cf5-497b-bb77-0cdbbd602d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permissions'])[1]/following::div[4]</value>
      <webElementGuid>d0b68512-398a-4afb-9277-72db64691791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Display name'])[1]/following::div[7]</value>
      <webElementGuid>61c9ca88-641e-49d2-9714-970a3dc132ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/preceding::div[7]</value>
      <webElementGuid>cfbcd43c-2d5a-42b6-9319-049d1a80fa63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[6]</value>
      <webElementGuid>ba6f0f0d-2b64-4c6c-be78-4787b8d5916c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>709ba280-0cf6-4a8b-8cdd-9cbf05e56e5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
