<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SystemddennisDashboardAuditsReportsAsse_a7b69b</name>
   <tag></tag>
   <elementGuidId>58788187-1f4d-4b79-831c-1c69611549ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-root']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.makeStyles-root-2638</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6d0a3a11-fe18-4e34-8adf-9551b0a5ad9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>makeStyles-root-2638</value>
      <webElementGuid>3a2615e6-afba-44cc-9a60-29632d27e2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SystemddennisDashboardAuditsReportsAssetsDataCheckSystemBranchesLocationsUsersEmailFirst nameSurnameDisplay namePermissionsAdmin, API, Auditor, Controller, ServiceSelected — 5/5SaveLocationBranchesAdminAPIAuditorControllerServiceMuseumplein 6, 1071 DJ Amsterdam, NetherlandsABC Motors - Sardinia15 Main St, Blackrock, Co. Dublin, A94 T8P8ABC Motors - DublinBennelong Point, Sydney NSW 2000, AustraliaHigh Beam Motor GroupLondon SW1A 0AA, United KingdomABC Motors - LondonChamp de Mars, 5 Av. Anatole France, 75007 Paris, FranceABC Motors - ParisPariser Platz,10117 Berlin, GermanyAuto Von Bismark20 W 34th St, New York, NY 10001,United StatesAxle Automotive GroupR400, 1911,South AfricaGroot Motors1600 Pennsylvania Avenue NW,Washington, DC 20500, United StatesAxle Automotive GroupRows per page:101-9 of 9</value>
      <webElementGuid>b00b8474-1901-4bba-bc18-8c760b9d78c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/div[@class=&quot;makeStyles-root-2638&quot;]</value>
      <webElementGuid>712cdceb-fd36-47e7-b841-8fcbfd2a0899</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div</value>
      <webElementGuid>425b7834-0271-41d1-bbbf-d5133af4029e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>ca0203ea-88a0-435d-b8a4-13a9ef68b6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'SystemddennisDashboardAuditsReportsAssetsDataCheckSystemBranchesLocationsUsersEmailFirst nameSurnameDisplay namePermissionsAdmin, API, Auditor, Controller, ServiceSelected — 5/5SaveLocationBranchesAdminAPIAuditorControllerServiceMuseumplein 6, 1071 DJ Amsterdam, NetherlandsABC Motors - Sardinia15 Main St, Blackrock, Co. Dublin, A94 T8P8ABC Motors - DublinBennelong Point, Sydney NSW 2000, AustraliaHigh Beam Motor GroupLondon SW1A 0AA, United KingdomABC Motors - LondonChamp de Mars, 5 Av. Anatole France, 75007 Paris, FranceABC Motors - ParisPariser Platz,10117 Berlin, GermanyAuto Von Bismark20 W 34th St, New York, NY 10001,United StatesAxle Automotive GroupR400, 1911,South AfricaGroot Motors1600 Pennsylvania Avenue NW,Washington, DC 20500, United StatesAxle Automotive GroupRows per page:101-9 of 9' or . = 'SystemddennisDashboardAuditsReportsAssetsDataCheckSystemBranchesLocationsUsersEmailFirst nameSurnameDisplay namePermissionsAdmin, API, Auditor, Controller, ServiceSelected — 5/5SaveLocationBranchesAdminAPIAuditorControllerServiceMuseumplein 6, 1071 DJ Amsterdam, NetherlandsABC Motors - Sardinia15 Main St, Blackrock, Co. Dublin, A94 T8P8ABC Motors - DublinBennelong Point, Sydney NSW 2000, AustraliaHigh Beam Motor GroupLondon SW1A 0AA, United KingdomABC Motors - LondonChamp de Mars, 5 Av. Anatole France, 75007 Paris, FranceABC Motors - ParisPariser Platz,10117 Berlin, GermanyAuto Von Bismark20 W 34th St, New York, NY 10001,United StatesAxle Automotive GroupR400, 1911,South AfricaGroot Motors1600 Pennsylvania Avenue NW,Washington, DC 20500, United StatesAxle Automotive GroupRows per page:101-9 of 9')]</value>
      <webElementGuid>4b52a49a-2e27-43f2-9c49-b490ff0357b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
