<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_First name</name>
   <tag></tag>
   <elementGuidId>1ed276aa-65f4-4063-9c1b-7ac6f1c47b86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-root']/div/div[2]/div/div/div/div/form/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a58a127e-1a3e-4e95-8bc4-25f751869af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormControl-root MuiTextField-root</value>
      <webElementGuid>b495207a-7c44-415f-93a0-0a3e3731df23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>First name</value>
      <webElementGuid>6bc9f820-35e3-4f96-852f-91e0bbb40586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/div[@class=&quot;makeStyles-root-2557&quot;]/div[@class=&quot;makeStyles-main-2555&quot;]/div[@class=&quot;makeStyles-content-2554&quot;]/div[@class=&quot;makeStyles-container-2586&quot;]/div[@class=&quot;MuiGrid-root makeStyles-fullHeight-2590 MuiGrid-container&quot;]/div[@class=&quot;MuiGrid-root makeStyles-content-2589 MuiGrid-item MuiGrid-grid-xs-4&quot;]/form[1]/div[@class=&quot;MuiFormControl-root MuiFormControl-marginNormal MuiFormControl-fullWidth&quot;]/div[@class=&quot;MuiFormControl-root MuiTextField-root&quot;]</value>
      <webElementGuid>142b9f21-b7ab-4348-8464-1a45c2fcc23f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div/div[2]/div/div/div/div/form/div[2]/div</value>
      <webElementGuid>87463400-5eb0-4c38-aa36-6d3e2108a1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::div[3]</value>
      <webElementGuid>855451d3-cb8b-43c3-9278-998a2ec12137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::div[8]</value>
      <webElementGuid>b175486c-2e78-4c7d-b0a7-14997ea9f0bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surname'])[1]/preceding::div[2]</value>
      <webElementGuid>a862fbe8-83c4-4061-9c21-c3fbde9a19e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div</value>
      <webElementGuid>28863624-5e07-4e6d-a8ab-651aa78c2198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'First name' or . = 'First name')]</value>
      <webElementGuid>98c702bb-265e-4a50-9414-431ba716f74e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
