<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Branches</name>
   <tag></tag>
   <elementGuidId>d5392544-5ef0-4e92-b031-80f84560029c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-root']/div/div[2]/div/header/div/div[2]/div/button[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a08716c0-1faa-40c8-824e-5234bd29a2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTab-wrapper</value>
      <webElementGuid>61eaac64-020a-4d0e-80cf-1fbf72a8aa37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Branches</value>
      <webElementGuid>62ac1003-8338-4690-88b3-576c1684e722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/div[@class=&quot;makeStyles-root-1003&quot;]/div[@class=&quot;makeStyles-main-1001&quot;]/div[@class=&quot;makeStyles-content-1000&quot;]/header[@class=&quot;MuiPaper-root MuiAppBar-root MuiAppBar-positionStatic MuiAppBar-colorTransparent MuiPaper-elevation0&quot;]/div[@class=&quot;MuiTabs-root&quot;]/div[@class=&quot;MuiTabs-scroller MuiTabs-scrollable&quot;]/div[@class=&quot;MuiTabs-flexContainer&quot;]/button[@class=&quot;MuiButtonBase-root MuiTab-root MuiTab-textColorPrimary&quot;]/span[@class=&quot;MuiTab-wrapper&quot;]</value>
      <webElementGuid>c79a3a2f-7029-490b-9d8f-9503d0e5860e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div/div[2]/div/header/div/div[2]/div/button[2]/span</value>
      <webElementGuid>83875dac-3d2f-44bb-bbde-ea8e336212df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System'])[2]/following::span[4]</value>
      <webElementGuid>ad12e19f-f9c9-4c8b-ac4d-79fe27fe7ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DataCheck'])[1]/following::span[7]</value>
      <webElementGuid>d824eb04-3b25-4217-a912-053382f84419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locations'])[1]/preceding::span[4]</value>
      <webElementGuid>921f6139-cd3f-4209-9528-6191b6558ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/preceding::span[6]</value>
      <webElementGuid>b41782a2-6706-4ddc-bf8d-c5413d0509e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Branches']/parent::*</value>
      <webElementGuid>025dcb94-51a9-4d2d-8848-9aa1f814a49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>2f4c3391-7102-4291-a0b9-ed3e207a57f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Branches' or . = 'Branches')]</value>
      <webElementGuid>6a5fe152-7192-4542-b40a-570cde4481c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
