<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_System</name>
   <tag></tag>
   <elementGuidId>1efff23a-bdcb-4f21-a05e-73a8b51e4596</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-root']/div/div/div/div[7]/div[2]/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.makeStyles-root-516.makeStyles-root-517</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a00c3980-6c54-4462-94b9-95d8245807dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>makeStyles-root-516 makeStyles-root-517</value>
      <webElementGuid>4b0e4d32-744a-42cd-b71a-d7df489fbc94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>System</value>
      <webElementGuid>49af7055-1595-4eb2-b706-d83e3b4b5b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/div[@class=&quot;makeStyles-root-489&quot;]/div[@class=&quot;MuiDrawer-root MuiDrawer-docked makeStyles-drawer-502&quot;]/div[@class=&quot;MuiPaper-root MuiDrawer-paper makeStyles-drawerPaper-504 MuiDrawer-paperAnchorLeft MuiDrawer-paperAnchorDockedLeft MuiPaper-elevation0&quot;]/div[@class=&quot;MuiButtonBase-root MuiListItem-root makeStyles-listItem-505 MuiListItem-gutters MuiListItem-button&quot;]/div[@class=&quot;MuiListItemText-root&quot;]/span[@class=&quot;MuiTypography-root MuiListItemText-primary MuiTypography-body1 MuiTypography-colorInherit MuiTypography-displayBlock&quot;]/span[@class=&quot;makeStyles-root-516 makeStyles-root-517&quot;]</value>
      <webElementGuid>a1e89809-2ea1-48df-bff8-cf52965b3e0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div/div/div/div[7]/div[2]/span/span</value>
      <webElementGuid>4f83828d-cb6c-4089-b69d-fd86ca5d3c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DataCheck'])[1]/following::span[3]</value>
      <webElementGuid>05903425-e40a-4763-b168-b7c0f8aab09c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assets'])[1]/following::span[6]</value>
      <webElementGuid>7b297bfb-7242-4541-af0b-e634a011b53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='System']/parent::*</value>
      <webElementGuid>ae6212fe-aa6c-4221-a4cc-02abd13fd8e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/span/span</value>
      <webElementGuid>d450c731-5003-4548-8ca1-78ccc798a7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'System' or . = 'System')]</value>
      <webElementGuid>5b89f245-e3e8-4028-a500-b1d65af95224</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
