<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Users_MuiSvgIcon-root</name>
   <tag></tag>
   <elementGuidId>1fd8f6d5-9933-4d7e-bb52-9ba6478c4047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::*[name()='svg'][2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.makeStyles-toolbarActionsRight-1096 > button.MuiButtonBase-root.MuiIconButton-root > span.MuiIconButton-label > svg.MuiSvgIcon-root</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>839c8caa-04ea-4028-85d9-89c2bfc16072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSvgIcon-root</value>
      <webElementGuid>a78d5769-41a9-4871-95f8-544486fdbaa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9fe193ba-94a7-4a92-861c-acf778ff2083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>df45bb9e-6e6c-4f81-81db-8fc97f696db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>21d09e89-6214-4ce1-858d-3ed3c8ef4d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/div[@class=&quot;makeStyles-root-1042&quot;]/div[@class=&quot;makeStyles-main-1040&quot;]/div[@class=&quot;makeStyles-content-1039&quot;]/div[@class=&quot;makeStyles-container-1071&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-regular makeStyles-toolbar-1094 MuiToolbar-gutters&quot;]/div[@class=&quot;makeStyles-toolbarActionsRight-1096&quot;]/button[@class=&quot;MuiButtonBase-root MuiIconButton-root&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/svg[@class=&quot;MuiSvgIcon-root&quot;]</value>
      <webElementGuid>9895a2c7-338a-4c56-8494-0501e406facf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>ae416d56-6ebe-4aff-a1ab-d0633b364455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locations'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>9ea8ab29-a808-4a46-98c9-1e9706bcf6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>bbdc5abe-4e5c-47b2-95d2-01536a89336f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Display name'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>da171253-2289-43b8-8e76-5caa8e51cc7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
